### ISSUE TITLE
YABBA-1.10.2-0.5.1 crashing the game on startup with java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by rckymtnrfc** [LatvianModder/YABBA#26]
I know you closed this before but your posted comment to fix this error didn't work.

You mentioned adding compatlayer.  I'm using the latest for 1.10.2 which is 0.2.9.  

You also mentioned updating FTBLib but the latest version for 1.10.2 is 3.5.3, which I have (as did the original bug poster).

I've removed all other mods, so I just have Forge 2297, YABBA 1.10.2-0.5.1, Compatlayer 0.2.9 and FTBlib 3.5.3.  Still get the same crash.  - https://pastebin.com/8SMf5jte

**Comment by LatvianModder** [comment]
Latest version for FTBLib has been 3.6.5 for quite some time now

**Comment by rckymtnrfc** [comment]
But 3.6.5 is for Minecraft 1.11.2 and this crash is on 1.10.22.  Does 3.6.5 work on 1.10.2 also?

**Comment by LatvianModder** [comment]
What? It clearly says 1.1x not 1.11 or 1.10

**Comment by rckymtnrfc** [comment]
Ah, I wasn't even looking at the file name, just the supported version column.  Sorry for the confusion.
